### ISSUE TITLE
sending email via Application Settings -> email setup does not work

### ISSUE THREAD

**Issue by jorikcaljouw** [jorikcaljouw/spksrc#1]
reported by @unheilig:
as per email notifications (application settings -> email setup), I couldn't send any email although I was using a google account and following the same rules stated here: http://www.domoticz.com/wiki/Application_Settings. Any ideas?

**Comment by jorikcaljouw** [comment]
I have not tried emailing myself, but maybe you can inspect the Log file for any error messages? You can find the Log file via DSM / Package Center.

**Comment by unheilig** [comment]
hi all, 
log file for email sending attempt states the following:
![image](https://cloud.githubusercontent.com/assets/7802775/3440192/2f24a8a6-00f4-11e4-826f-0df8312bd878.png)

it looks like it's trying to send an email to a "!" address (obviously I had a valid email address there). any ideas?

**Comment by jorikcaljouw** [comment]
That looks indeed as if the To: email cannot be accurately retrieved when sending the email. I believe there is a test-button for verifying email settings, does that work correctly? And can you see the valid email address in the settings page?

I will confirm tonight at home if it works for me with gmail settings.

**Comment by unheilig** [comment]
1) yes there is a Test button that tries to do what it states (i assume it is working correctly, since test fails and a red message box appears);2) yes I can see my email displaying correctly in the edit field
thanks!

----Messaggio originale----

Da: notifications@github.com

Data: 1-lug-2014 12.07

A: "jorikcaljouw/spksrc"spksrc@noreply.github.com

Cc: "unheilig"unheilig@libero.it

Ogg: Re: [spksrc] sending email via Application Settings -> email setup does not work (#1)

That looks indeed as if the To: email cannot be accurately retrieved when sending the email. I believe there is a test-button for verifying email settings, does that work correctly? And can you see the valid email address in the settings page?

I will confirm tonight at home if it works for me with gmail settings.

**Comment by jorikcaljouw** [comment]
This works correctly for me (gmail). I have entered the following details. The part that is blurred out is my gmail address:
![screen shot 2014-07-02 at 00 58 45](https://cloud.githubusercontent.com/assets/7646814/3450118/8b69f9fc-0173-11e4-863a-071fbad0e8c9.png)

**Comment by unheilig** [comment]
without any clue. my screen is the following
![image](https://cloud.githubusercontent.com/assets/7802775/3452305/2da55252-01b0-11e4-8744-9c5a715f1007.png).

please note that on the same Synology, email Notification works perfectly, and the configuration is the following:
![image](https://cloud.githubusercontent.com/assets/7802775/3452532/938bed6a-01b5-11e4-93ad-38da06d114e4.png)

**Comment by jorikcaljouw** [comment]
Can you double check there are no spaces before or after the email addresses? The error message in the log seems to indicate there are issues retrieving the to: emailaddress when sending the email. These settings should be stored in the database file if I'm not mistaken.

**Comment by unheilig** [comment]
checked. no spaces at all, before nor after.

some other strange behaviour: 
- my gmail configuration, on DS411+ of my friend is working fine, 
- his gmail configuration on my synology is not working at all.

it looks like I have some (network) problem in my Domoticz. what could be (assuming that everything else in DSM5.0 is running fine)?

**Comment by jorikcaljouw** [comment]
Ok, so your gmail config does work on his, but not on your NAS.
And his gmail config does also work on his, but not on your NAS? That could point to an issue with email sending for the architecture of your NAS.

Only thing I noticed is that you configured DSM to use port 465, while Domoticz is configured to use 587. Could you try the same port configuration in Domoticz to rule out it is related to your network situation?

**Comment by unheilig** [comment]
yes, mine on his is working fine. his config on mine is not working, as long as mine on mine!
I also tried to use 465 on Domoticz, but it didn't work at all.

I noticed that the Red box with the error message ("please check your credentials") is (sometimes) also appearing on my friend's NAS (DS411+ x86), but working fine

(i'm going crazy). 

Maybe a JSON trouble on my compiled version?

**Comment by unheilig** [comment]
Hi Jorik, 
any idea on this issue? it looks like it's related to the particular version compiled for my model. 
or maybe some missing JSON component?

**Comment by unheilig** [comment]
hi guys,
one update on this. It looks like that in this compiled version of Domoticz it is not able to send emails due to a conversion of email addresses. 

Indeed, "@" sign is converted into %40 and maybe the command that is executed to send email can't catch the correct email address since it contains some "garbage"

please have a look at the image (the example is related to an API notification (PUSHOVER service).

![image](https://cloud.githubusercontent.com/assets/7802775/3764486/cfde9354-18b1-11e4-9237-feace73a5c68.png)

Indeed if I try to use PRAWL, that requires no userid authentication but the API key, notification is working correctly.

PLEASE HELP! thank you!

**Comment by jorikcaljouw** [comment]
Hi @unheilig,
sorry for the radio silence, I have been rather busy with other things and have not done much with the spksrc. I must say the lack of feedback from SynoCommunity for the pull request does not really motivate me... Anyway, %40 is the way to write @ with urlencoding. If the @ is somehow not correctly sent or stored by some browser setting, could you do some debugging with other browsers or other settings and see if that helps? If this is a bug, it is something that needs to be fixed by the domoticz developers(s), like gizmocuz. I wouldn't know where to start solving this ;-). And it would be helpful if they can reproduce the problem on their end, by using some specific browser and settings.

BTW, I have updated the Makefile for the latest revision (1853) and it still seems to build and work correctly on my computer. I am building all archs that used to work to verify if anything else breaks.

**Comment by unheilig** [comment]
hi Jorik,
thank you for your reply. Yes, I've tried also with other browsers (chrome, firefox, opera, ie), but I always get the same issue. no e-mail notifications are sent (and the error message it's always the following)

![image](https://cloud.githubusercontent.com/assets/7802775/3775941/15e502f2-194d-11e4-86ba-40c5c31c7b89.png)

Moreover, it often happens that domoticz hangs and crashes, and has to be stopped-restarted.

I can confirm that it works perfectly on the x86 compiled version, regardless of browser/charset; 

Maybe @gizmocuz can verify what could be wrong in the notification settings (mainly the SMTP configuration to send emails?)

thank you very much

**Comment by unheilig** [comment]
hi Jorik,

do you think there are some benefits in trying the latest revision (1853)? 
would you be so kind to recompile for the DS213 (marvel kirkwood)?

thank you in advance

**Comment by jorikcaljouw** [comment]
I didn't see anything in the changelogs that would indicate your issue would be resolved, but you never know ;-). I could be mistaken, but domoticz_88f6281_1853-1.spk is the right arch for the DS213, right?

It would also be good if you could verify that upgrading the package works correctly. It did seem to work correctly for me and I have investigated that copying the database for the upgrade should happen correctly. Nonetheless you may want to create a manual backup from the web interface to be sure.

**Comment by unheilig** [comment]
Yes, I had the "domoticz_88f6281_1812-1.spk" compiled for my DS213, that's right.
I will verify also the upgrade of the package, along with backuping/restoring the database.

thank you! let me know how to get the compiled version then!

G

**Comment by jorikcaljouw** [comment]
Oh, sorry, I thought the link I sent earlier would point you to the folder with both revisions, if it did not, this link should work:
https://www.dropbox.com/sh/hlf95h3lfq3tdht/AADWfUok2b4BZPaXMJgzyTxOa/SynoTestPackages

**Comment by unheilig** [comment]
hi. 
upgraded the version without any trouble. 
No data was lost.

and, unfortunately, no fix were made for the email notifications to work. :(

**Comment by Schim9** [comment]
Hi,

My Syno is configured to send me e-mail notification through Gandi.net
![image](https://cloud.githubusercontent.com/assets/8232585/3825794/7b2156ac-1d58-11e4-8bfc-742b04113e7d.png)

If I set the same thing in Domoticz 
![image](https://cloud.githubusercontent.com/assets/8232585/3825810/9fe094ee-1d58-11e4-87dd-74a7216a41e1.png)
=> Check your credential
![image](https://cloud.githubusercontent.com/assets/8232585/3825816/aed95878-1d58-11e4-85ea-e138418a148d.png)

Same issue for Pushover Android. I tried the UserID with @ and %40 but nothing work.
I created an application and I put the APITokenKEy
![image](https://cloud.githubusercontent.com/assets/8232585/3825915/1a2f88a8-1d5a-11e4-980b-55a25eb7717a.png)

Unsuccessfull.

But the NMA notification is working.

**Comment by unheilig** [comment]
yes, same issue as mine.
looks like NMA is working just because Domoticz doesn't handle ANY email address.. :(

**Comment by jorikcaljouw** [comment]
According to people in the domoticz forum this should be resolved in rev 2029. I'll create a package with the latest rev. on Sunday.

**Comment by jorikcaljouw** [comment]
I have added a package with rev 2042 for your arch to the same folder:
https://www.dropbox.com/sh/hlf95h3lfq3tdht/AADWfUok2b4BZPaXMJgzyTxOa/SynoTestPackages
Could you give it a try?

**Comment by unheilig** [comment]
Hi Jorik, thanks for your work.

I've just installed rev 2042 but unfortunately when trying to send an email Domoticz hangs infinitely, without returning a response. 
It also hangs the Web UI of all the DSM. 

I'm going to test it again trying to change the smtp server/ port (at the moment I'm using smtp.gmail.com and port 465)

thank you, please let's keep in touch

**Comment by jorikcaljouw** [comment]
Hmm, that does not sound good. I will test the same package on my DiskStation tonight, but I would find it very strange if this application could cause DSM to not respond anymore.

**Comment by unheilig** [comment]
I suppose it's the whole browser (Chrome) that hangs, not the DSM itself... 
anyway please have a look at email notification procedure.

thank you!

**Comment by unheilig** [comment]
Hi Jorik,
did you have the chance to try to investigate further into this?
thank you

**Comment by jorikcaljouw** [comment]
Sorry, haven't tried the 2042 on my NAS yet. I want to do this first, confirm that emailing works correctly for x86 arch, before getting back to Domoticz devs. Can you make some more screenshots about rev 2042 and do we still see encoding issues for the email settings? (So not for the pushover settings)

**Comment by unheilig** [comment]
Hi Jorik,

yes I confirm that on x86 arch email notification works perfectly. 
I have noticed that as per email settings (not for pushover / other APIs) there are no encoding issues on Domoticz rev 2042. you can have a look at the following image:

![image](https://cloud.githubusercontent.com/assets/7802775/4556651/9c726cb6-4ecb-11e4-8f4a-aa96abd07bcc.png)

as you can see, it looks like that still there is some problem in the email settings

thank you

**Comment by Schim9** [comment]
Hi @jorikcaljouw ,

I m sorry for giving no news for the last weeks, I was quite busy and as I did not succeed in installing my RFXTrx433E I was quite demotivated.

Today I have succeeded in installing my transceiver (thanks to a spk with the good USB driver)
=> http://lebovitz.co.il/SPK/UsbSerialDrivers_2.0.0.spk

I have installed the 2042 release and the mail notification seems to work well :
![image](https://cloud.githubusercontent.com/assets/8232585/4881642/a69b1276-634b-11e4-9db2-2c53883f302f.png)

**Comment by unheilig** [comment]
Hi all,

email notification on version 2042 for Marwell Kirkwood processor still doesn't work.
does anyone of you succeded in email notifications for that distribution?

@Schim57300: which DS model do you have?
@jorikcaljouw: any news?

**Comment by Schim9** [comment]
I have installed domoticz_88f6281_2042-4.spk on my DS410J.
The DSM is DSM 5.0-4493 Update 3 from 19/07/2014.

Does that answer you ?

In my test I have set the Gandi mail server (webmail.gandi.net:25)

**Comment by unheilig** [comment]
hi @Schim57300, so we run the same spk on the same DSM os. 
the only thing that differs as per this issue is the smtp server, i'm using smtp.google.com:465 but it doesn't work. I've also tried port 25 and 587, but It didn't worked. 

are you able to try with smtp.google.com:465?

thank you

**Comment by Schim9** [comment]
I have just tried with my google account and it does not work.
=> smtp.google.com:25
=> smtp.google.com:465

Maybe the problem come from Gmail...

**Comment by jorikcaljouw** [comment]
Outgoing connection on port 25 to smtp servers outside your ISP network will typically not work, because all ISP's that I know block it to prevent spam. I believe Gmail requires encryption (TLS or SSL) for ports 465 and 587, which could fail if something was not compiled correctly with SSL support. Would it be possible to test this with an SMTP server by your internet provider which will probably accept emails sent to port 25?

**Comment by Schim9** [comment]
For me it work on port 25 through the Gandi smtp server : 
![image](https://cloud.githubusercontent.com/assets/8232585/4882878/f497b21c-635b-11e4-9028-b08d538f2f28.png)

**Comment by unheilig** [comment]
unfortunately it seems that the only smtp server that I'm able to use (smtp.tiscali.it) with port 25 is not working for the notifications:

![image](https://cloud.githubusercontent.com/assets/7802775/4883229/f75b1f76-635f-11e4-8b4e-52faecdcf9ba.png)

any ideas?

**Comment by Schim9** [comment]
Sorry I won't be able to try with another mailbox :-\

If I would encounter another problem with this release (that I didn't with the previously installed one) where should I describe it ? It is not related to Notifications....

Thanks

**Comment by gizmocuz** [comment]
most ISPs do NOT allow connecting to port 25 from outside your home connection, could this be it?
Or use google, and let google forward te mail to you

**Comment by Schim9** [comment]
I confirm in France some ISP prevent the use of the port 25 to send e-mail (Orange...)

**Comment by unheilig** [comment]
hi @gizmocuz, using google smtp won't help, since SSL authentication is not working in version 2042-4. 
or you meant something different?

**Comment by gizmocuz** [comment]
There have been people using gmail since the more then a year, it should work

**Comment by Schim9** [comment]
Excuse me to be off-topic but it seems there is an issue with the package domoticz_88f6281_2042-4.spk
When Domoticz is started, the /usr/local/domoticz/www folder contains .gz files instead of .js
![image](https://cloud.githubusercontent.com/assets/8232585/4896842/e7532e3e-63ff-11e4-9f64-332a8aeb4aa3.png)

If you activate the secure remote access you will have a lot of error in your browser
![image](https://cloud.githubusercontent.com/assets/8232585/4896841/e1b84946-63ff-11e4-8c4e-74097b1317dc.png)

I had to run the following commands : 
Cd /usr/local/domoticz/www/
find . -name *.gz
gunzip –r *

I still had error related to 4 angular files. I did : 
Cd /usr/local/domoticz/www/js
cp angular-animate.min.js angular-animate.min.js.map
cp angular.min.js angular.min.js.map
cp angular-route.min.js angular-route.min.js.map
cp angular-sanitize.min.js angular-sanitize.min.js.map

I still have an issue when I connect myself via my local network but I think it is related to my Synology firewall configuration : 
![image](https://cloud.githubusercontent.com/assets/8232585/4896868/2fb041f8-6400-11e4-9c5c-3a186689925a.png)

When I am really away everything work successfully.
Even Dromotica

Schim'

**Comment by gizmocuz** [comment]
You should not do this, the .gz files are send over with a gzip HTTP header to the client, this has been working for year(s) now, so no need to unpack them
If you use another webserver then the build in, maybe you have a problem, but thats not a domoticz problem

**Comment by unheilig** [comment]
unfortunately @gizmocuz gmail doesn't work. 

can you probe that smtp.google.com:465 or 587 is sending email correctly?

@jorikcaljouw do you think it is possible to investigate in SSL authentication for email sending?

**Comment by Schim9** [comment]
@gizmocuz ,
Thank you for your answer. I used to have the domoticz_88f6281_1853-1.spk with no problem.
Yesterday I have installed the domoticz_88f6281_2042-4.spk and it does not work without gunzip on your .js files.

Maybe I have done something wrong.

**Comment by jorikcaljouw** [comment]
There were a couple of improvements made between 1853-1 and 2042-4. I'm not sure if upgrading directly from the old to the new works 100% correctly. Could you maybe backup the database manually (from Domoticz itself), then remove the Domoticz package and install 2042-4? Then reload the database manually?

**Comment by jorikcaljouw** [comment]
@unheilig if non-SSL to your ISP SMTP server also does not work, I think we should be looking into this before looking into SSL issues. I wonder if it would be easy to log all data that is actually sent via SMTP with wireshark or something similar.

**Comment by unheilig** [comment]
@jorikcaljouw yes, also port 25 is not working, you're right. 
i will try to investigate with tshark, and please if you have news about smtp email sending please advice

thank you

**Comment by Schim9** [comment]
@jorikcaljouw I did uninstall the package yesterday. Then I installed the new one.

I do not understand why that does not work. Maybe I should try a previsous version.

**Comment by Schim9** [comment]
For your information my problems are solves.
By switching the security settings to Basic Auth, I do not have any js exception anymore.
![image](https://cloud.githubusercontent.com/assets/8232585/4915790/96a69e98-64d2-11e4-8efe-0cc83ff40386.png)

My Domoticz server works correctly on my Synology : 
- accessing the website from everywhere with several browser (IE, Chrome, Android browser)
- scheduling blinds closure and opening
- sending mail notification throught my Gandi webmail
- Managing the devices and executing scenes via Dromotica on my smartphone.

It remains an issue when I want to list devices on Andromoticz. A mail has been sent to the support :-)

@jorikcaljouw : Do you need me to test anything else ?

Current release : domoticz_88f6281_2020-4.spk

Schim'

**Comment by unheilig** [comment]
hi @Schim57300, I've tried your suggestion as per login method, but unfortunately nothing changed by my side.

**Comment by Schim9** [comment]
Changing the loging method has solved my "js exception" problem.
Your problem is related to the mail notification isn't it ? Or do you have also remote connection problem? 

Regarding the notifications, would it help you if I would create a dummy mailbox on my gandi account and I provide you with the connection identifiers ? You would be able to try the notification on your side :-\

**Comment by unheilig** [comment]
@Schim57300 that could be a great idea to deal with. you can email me at unheilig at libero dot it.

thank you!

**Comment by Schim9** [comment]
done.

**Comment by unheilig** [comment]
As stated by @Schim57300, email notification through smtp port 25 works with Domoticz! 
thank you!

so it could be useful to understand why SSL authentication is not properly working...

**Comment by gizmocuz** [comment]
Make take out the code, build a small test app with it ? And debug line by line
You could use codelite for IDE for example, or qt creator

**Comment by jorikcaljouw** [comment]
I am making some last small changes to my fork of spksrc for domoticz, then I will create a PR and then I'm closing my fork. In this time frame I will not be looking into possible SSL issues on 88f6281. Hence closing this issue in this fork

**Comment by gizmocuz** [comment]
latest svn version now has SSL build in

**Comment by unheilig** [comment]
ssl-tls on port 587 runs smoothly.
thank you for your work
