### ISSUE TITLE
icon not appearing in applications menu

### ISSUE THREAD

**Issue by jorikcaljouw** [jorikcaljouw/spksrc#2]
as reported by @unheilig
after installation, the icon of Domoticz is not appearing in the applications menu: so if you want to access Domoticz webpage  you have to open the Package center, find the app and then click on the link (http://yourip:8084). maybe you can add it to that menu?

**Comment by jorikcaljouw** [comment]
I am not sure why it is not showing for you. I know it does show up for me in the Applications menu. I will remove the application then remove all traces on my Synology and see what happens if I re-install. Maybe for me there was still something stored that caused the App to show up.

**Comment by unheilig** [comment]
unfortunately the icon is not showing neither on DS213 nor on DS411+

**Comment by jorikcaljouw** [comment]
You do mean something like this, right?
![domo-app-icon](https://cloud.githubusercontent.com/assets/7646814/3443326/342a70ba-0121-11e4-873d-28a708b9d1a6.png)

**Comment by unheilig** [comment]
yes! right in that way

**Comment by jorikcaljouw** [comment]
Sorry, I have no clue why it does not show up on your NAS. I have fully removed the package, searched for all files with "domo" in it, removed all traces and reinstalled the x86 package. Afterwards I immediately saw the package under Applications menu.
Do you have any other SynoCommunity packages? Do they all have shortcuts in the Applications menu?

**Comment by unheilig** [comment]
Yes, I have other packages by SynoCommunity, like TVHeadend, and it shows up correctly (please take a look below)
![image](https://cloud.githubusercontent.com/assets/7802775/3452274/59f9dbd0-01af-11e4-90b0-db15fb2ffbe3.png)

**Comment by unheilig** [comment]
and this is the package, installed
![image](https://cloud.githubusercontent.com/assets/7802775/3452283/8b6d2064-01af-11e4-9b12-ca160e96c45a.png)

**Comment by jorikcaljouw** [comment]
That's really odd. I think we may need to ask for some support from SynoCommunity on how to debug this issue. I have asked the other testers of my package. I have not yet heard back from steef84, but somebody from the domoticz forum replied that he did also see the package for his NAS just like me.
You may want to ssh into your NAS and inspect some of the folders that contains the necessary files for these Apps to work correctly. I'm not sure what these are exactly, but I can take a look.

**Comment by unheilig** [comment]
ok, I'll try to investigate via ssh. 
Actually I suggest this is a low-priority issue, anyway, it has a good workaround.

**Comment by jorikcaljouw** [comment]
Yes, I agree, I assume the link from the Package Center does work, right?

**Comment by unheilig** [comment]
yes, working like a charm ;)

**Comment by jorikcaljouw** [comment]
Hi unheilig, could you try removing the package and installing a newer version? I'd like to know if the icon that is not showing up is still an issue with the latest package: _2014-3. It is available in the same shared dropbox folder:
https://www.dropbox.com/sh/hlf95h3lfq3tdht/AADWfUok2b4BZPaXMJgzyTxOa/SynoTestPackages

Please backup your data and really remove the package and install the newer version instead of upgrading the package.

**Comment by jorikcaljouw** [comment]
Actually can you try 2020_4 ? It is in the same folder, please also comment in https://github.com/jorikcaljouw/spksrc/issues/1 to see if that is then also resolved. If not I'd like to ask the domoticz developers what we can do to find out what should be fixed.

**Comment by unheilig** [comment]
hi Jorik, 
yes it is finally working perfectly! 
I can see the icon either in 2014-3 or in the new 2020_4. (please see image)

So the only big thing that has been left is the E-Mail notification: still it is impossible to let the system send an email thru smtp configuration. Do you think it is possible to ask Domoticz for that other issue?

![image](https://cloud.githubusercontent.com/assets/7802775/4437887/3f6cf1f6-47a2-11e4-8db9-cc4b2aceb8b4.png)

THANK YOU Jorik for your work

**Comment by jorikcaljouw** [comment]
Ok great, so this is solved. I will ask domoticz devs what we can do about the email issue.

**Comment by unheilig** [comment]
thank you Jorik, hope to hear from you soon on that other matter!
